[window]
opacity = 0.85

[font]
    size = 12.0 # Adjust font size as desired

    [font.normal]
    family = "JetBrainsMono Nerd Font" # Use "JetBrainsMono" if not using Nerd Font
    style = "Regular"

    [font.bold]
    family = "JetBrainsMono Nerd Font" # Use "JetBrainsMono" if not using Nerd Font
    style = "Bold"

    [font.italic]
    family = "JetBrainsMono Nerd Font" # Use "JetBrainsMono" if not using Nerd Font
    style = "Italic"

    [font.bold_italic]
    family = "JetBrainsMono Nerd Font" # Use "JetBrainsMono" if not using Nerd Font
    style = "Bold Italic"
