services:
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        volumes:
            - ~/data/uptime-kuma/data:/app/data
        ports:
            - 8065:3001
        restart: always

